# Packages required

# options(pkgType="binary")
# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# 
# BiocManager::install("BiocGenerics")

#library(eulerr)
library(tidyverse)
library(readr)
library(tibble)
library(BiocGenerics)
library(forcats)
library(ggrepel)
library(ggdendro)
library(plyr)
library(fastcluster)
library(dendextend)
library(Hmisc)
library(readxl)
library(hrbrthemes)
library(tm)
library(proustr)
library(RColorBrewer)
library(VennDiagram)
library(UpSetR)
library(ggsci)
library(psych)
library(svglite)
library(ggpubr)
library(doParallel)
library(magrittr)
library(glue)

